name: Python version test
on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: cloning
        uses: actions/checkout@v4
      - name: install poetry
        run: pipx install poetry
      - name: install Python
        uses: actions/setup-python@v5
        with:
          python-version: '${{ inputs.python-version }}
          cache: 'poetry'
      - name: add deps
        run: poetry install
      - name: test
        run: pytest -vv

