name: Python version test
on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: cloning
        uses: actions/checkout@v4
      - name: install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: install poetry
        run: |
          pip install poetry==1.8.3 
          poetry config virtualenvs.create false
      - name: add deps
        run: poetry install
      - name: test
        run: pytest -vv

