name: First
on: [workflow_dispatch]
jobs: 
  test_windows:
    runs-on:  ubuntu-latest
    steps:
                 
      - name: clone
        uses: actions/checkout@v4
      - name : install dependecies
        run : pip install -r requirements.txt
      - name: run
        run : python main.py
       
    
  
