name: Python version test
on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
env:
  ACTIONS_TEST: true        
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-pypoetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-pypoetry-
      - name: cloning
        uses: actions/checkout@v4
      - name: install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: install poetry
        run: |
          pip install poetry==1.8.3 
          poetry config virtualenvs.create false
      - name: add deps
        run: |
          poetry install --no-root
      - run: echo "${{ env.ACTIONS_TEST }}"
      - name: test
        run: pytest -vv

