name: ubuntu-latest macos-latest windows-latest
on: push
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: ["3.12", "3.13"]
        include:
          - os: ubuntu-latest
            path: ~/.cache/pypoetry
          - os: macos-latest
            path: ~/Library/Caches/pypoetry
          - os: windows-latest
            path: ~\AppData\Local\pypoetry\Cache
    steps:
    - uses: actions/cache@v4
      with:
        path: ${{ matrix.path }}
        key: ${{ runner.os }}-pypoetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-pypoetry-
    - name: cloning
      uses: actions/checkout@v4.2.2
    - name: install Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.version }}
    - name: install poetry
      run: |
        pip install poetry==1.8.3 
        poetry config virtualenvs.create false
    - name: add deps
      run: |
        poetry install --no-root
    - name: test
      run: pytest -vv

